package codegen

import (
	"github.com/lazygophers/log"
	"github.com/lazygophers/utils/app"
	"strconv"
	"time"
)

func getFileHeader(pb *PbPackage) []byte {
	now := time.Now()

	b := log.GetBuffer()
	defer log.PutBuffer(b)

	b.WriteString("// Code generated by ")
	b.WriteString(app.Name)
	b.WriteString(". DO NOT EDIT.")
	b.WriteByte('\n')

	// 版本
	b.WriteString("//\tversions:\n")

	b.WriteString("//\t\t")
	b.WriteString(app.Name)
	b.WriteByte('\t')
	b.WriteByte('v')
	b.WriteString(app.Version)
	b.WriteByte('\n')

	b.WriteString("//\t\tgo\t\t")
	b.WriteString(app.GoVersion)
	b.WriteByte('\n')

	// 更新时间
	b.WriteString("//\tupdate:\t")
	b.WriteString(strconv.FormatInt(now.Unix(), 10))
	b.WriteByte('\n')

	// 文件
	if pb != nil {
		b.WriteString("//\tsource: ")
		b.WriteString(pb.ProtoFileName())
		b.WriteByte('\n')
	}

	b.WriteByte('\n')

	// Code generated by protoc-gen-go. DO NOT EDIT.
	// versions:
	// 	protoc-gen-go v1.33.0
	// source: example.proto
	// update: 1716956316

	return b.Bytes()
}
