package codegen

import (
	"github.com/lazygophers/log"
	"github.com/lazygophers/utils/app"
)

func getFileHeader(pb *PbPackage) []byte {
	b := log.GetBuffer()
	defer log.PutBuffer(b)

	b.WriteString("// Code generated by ")
	b.WriteString(app.Name)
	b.WriteString(". DO NOT EDIT.")
	b.WriteByte('\n')

	b.WriteString("// versions:\n")

	b.WriteString("//    ")
	b.WriteString(app.Name)
	b.WriteByte('\t')
	b.WriteByte('v')
	b.WriteString(app.Version)
	b.WriteByte('\n')

	b.WriteString("//    go\t\t")
	b.WriteString(app.GoVersion)
	b.WriteByte('\n')

	b.WriteString("// source: ")
	b.WriteString(pb.ProtoFileName())
	b.WriteByte('\n')

	b.WriteByte('\n')

	// Code generated by protoc-gen-go. DO NOT EDIT.
	// versions:
	// 	protoc-gen-go v1.33.0
	// source: example.proto

	return b.Bytes()
}
