// Code generated by codegen. DO NOT EDIT.
//	versions:
//		codegen	v0.0.0-SNAPSHOT-2f7005e
//		go		go1.22.3
//	update:	1717862981

package state

const (
	I18nTagCliFlagsDebug		= `cli.flags.debug`
	I18nTagCliGenAddRpcFlagsAction		= `cli.gen.add-rpc.flags.action`
	I18nTagCliGenAddRpcFlagsDefaultRole		= `cli.gen.add-rpc.flags.default-role`
	I18nTagCliGenAddRpcFlagsGenTo		= `cli.gen.add-rpc.flags.gen-to`
	I18nTagCliGenAddRpcFlagsListOption		= `cli.gen.add-rpc.flags.list-option`
	I18nTagCliGenAddRpcFlagsModel		= `cli.gen.add-rpc.flags.model`
	I18nTagCliGenAddRpcLong		= `cli.gen.add-rpc.long`
	I18nTagCliGenAddRpcShort		= `cli.gen.add-rpc.short`
	I18nTagCliGenAllLong		= `cli.gen.all.long`
	I18nTagCliGenAllShort		= `cli.gen.all.short`
	I18nTagCliGenCacheLong		= `cli.gen.cache.long`
	I18nTagCliGenCacheShort		= `cli.gen.cache.short`
	I18nTagCliGenCmdLong		= `cli.gen.cmd.long`
	I18nTagCliGenCmdShort		= `cli.gen.cmd.short`
	I18nTagCliGenFlagsAddProtoFiles		= `cli.gen.flags.add-proto-files`
	I18nTagCliGenFlagsGoModulePrefix		= `cli.gen.flags.go-module-prefix`
	I18nTagCliGenFlagsInput		= `cli.gen.flags.input`
	I18nTagCliGenFlagsOutputPath		= `cli.gen.flags.output-path`
	I18nTagCliGenFlagsOverwrite		= `cli.gen.flags.overwrite`
	I18nTagCliGenFlagsProtoFiles		= `cli.gen.flags.proto-files`
	I18nTagCliGenFlagsProtoc		= `cli.gen.flags.protoc`
	I18nTagCliGenFlagsProtocGenGo		= `cli.gen.flags.protoc-gen-go`
	I18nTagCliGenFlagsTablesEnableFieldCreatedAt		= `cli.gen.flags.tables-enable_field_created_at`
	I18nTagCliGenFlagsTablesEnableFieldDeletedAt		= `cli.gen.flags.tables-enable_field_deleted_at`
	I18nTagCliGenFlagsTablesEnableFieldId		= `cli.gen.flags.tables-enable_field_id`
	I18nTagCliGenFlagsTablesEnableFieldUpdatedAt		= `cli.gen.flags.tables-enable_field_updated_at`
	I18nTagCliGenFlagsTablesEnableGormTagColumn		= `cli.gen.flags.tables-enable_gorm_tag_column`
	I18nTagCliGenLong		= `cli.gen.long`
	I18nTagCliGenShort		= `cli.gen.short`
	I18nTagCliHelpAdditionalCommands		= `cli.help.additional_commands`
	I18nTagCliHelpAliases		= `cli.help.aliases`
	I18nTagCliHelpAvailableCommands		= `cli.help.available_commands`
	I18nTagCliHelpCommand		= `cli.help.command`
	I18nTagCliHelpFlags		= `cli.help.flags`
	I18nTagCliHelpGetInfo		= `cli.help.get_info`
	I18nTagCliHelpGlobalFlags		= `cli.help.global_flags`
	I18nTagCliHelpUse		= `cli.help.use`
	I18nTagCliI18nLong		= `cli.i18n.long`
	I18nTagCliI18nShort		= `cli.i18n.short`
	I18nTagCliI18nTranFlagsAllLanguage		= `cli.i18n.tran.flags.all-language`
	I18nTagCliI18nTranFlagsForce		= `cli.i18n.tran.flags.force`
	I18nTagCliI18nTranFlagsForceKeyPrefix		= `cli.i18n.tran.flags.force-key-prefix`
	I18nTagCliI18nTranFlagsGenerateConst		= `cli.i18n.tran.flags.generate-const`
	I18nTagCliI18nTranFlagsLanguages		= `cli.i18n.tran.flags.languages`
	I18nTagCliI18nTranFlagsSrcFile		= `cli.i18n.tran.flags.src-file`
	I18nTagCliI18nTranFlagsSrcLanguage		= `cli.i18n.tran.flags.src-language`
	I18nTagCliI18nTranFlagsTranslaterGoogleFree		= `cli.i18n.tran.flags.translater.google-free`
	I18nTagCliI18nTranFlagsTranslaterUsage		= `cli.i18n.tran.flags.translater.usage`
	I18nTagCliI18nTranLong		= `cli.i18n.tran.long`
	I18nTagCliI18nTranShort		= `cli.i18n.tran.short`
	I18nTagCliLong		= `cli.long`
	I18nTagCliShort		= `cli.short`
)
