// Code generated by codegen. DO NOT EDIT.
//	versions:
//		codegen	v0.0.0-SNAPSHOT-24cf78b
//		go		go1.22.3
//	update:	1717846603

package state

const (
	I18nTagCliFlagsDebug		= `cli.flags.debug`
	I18nTagCliHelpAdditionalCommands		= `cli.help.additional_commands`
	I18nTagCliHelpAliases		= `cli.help.aliases`
	I18nTagCliHelpAvailableCommands		= `cli.help.available_commands`
	I18nTagCliHelpCommand		= `cli.help.command`
	I18nTagCliHelpFlags		= `cli.help.flags`
	I18nTagCliHelpGetInfo		= `cli.help.get_info`
	I18nTagCliHelpGlobalFlags		= `cli.help.global_flags`
	I18nTagCliHelpUse		= `cli.help.use`
	I18nTagCliI18nLong		= `cli.i18n.long`
	I18nTagCliI18nShort		= `cli.i18n.short`
	I18nTagCliI18nTranFlagsAllLanguage		= `cli.i18n.tran.flags.all-language`
	I18nTagCliI18nTranFlagsForce		= `cli.i18n.tran.flags.force`
	I18nTagCliI18nTranFlagsForceKeyPrefix		= `cli.i18n.tran.flags.force-key-prefix`
	I18nTagCliI18nTranFlagsGenerateConst		= `cli.i18n.tran.flags.generate-const`
	I18nTagCliI18nTranFlagsLanguages		= `cli.i18n.tran.flags.languages`
	I18nTagCliI18nTranFlagsSrcFile		= `cli.i18n.tran.flags.src-file`
	I18nTagCliI18nTranFlagsSrcLanguage		= `cli.i18n.tran.flags.src-language`
	I18nTagCliI18nTranFlagsTranslaterGoogleFree		= `cli.i18n.tran.flags.translater.google-free`
	I18nTagCliI18nTranFlagsTranslaterUsage		= `cli.i18n.tran.flags.translater.usage`
	I18nTagCliI18nTranLong		= `cli.i18n.tran.long`
	I18nTagCliI18nTranShort		= `cli.i18n.tran.short`
	I18nTagCliLong		= `cli.long`
	I18nTagCliShort		= `cli.short`
)
